services:
  db:
    container_name: maria-db
    image: mariadb:10.6.4
    environment:
      - MARIADB_DATABASE=springsecurity
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - TZ=Asia/Seoul
      - LANG=C.UTF-8
    volumes:
      - ./doc/database:/database:ro
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "13307:3306"